/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Eval.Eval.Eval;
import static Eval.Eval.isParser;
import Graficador.Graficador2D;
import Graficador.GraficadorClasico;
import Reporte.IntervalosCerradosDS;
import Reporte.IntervalosCerradosSetGet;
import com.keffect.effects.animatedEffects.ZoomIn;
import com.keffectpanel.KEffectPanel;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Reymundo Tenorio
 */
public class IntervalosCerradosP extends javax.swing.JFrame {

    /**
     * Creates new form IntervalosAbiertosP
     */
    public IntervalosCerradosP() {

        try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }

        initComponents();
        Variable.setTransferHandler(null);
        Ea.setTransferHandler(null);
        Xi.setTransferHandler(null);
        Xu.setTransferHandler(null);

        // this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncancel = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Variable = new javax.swing.JTextField();
        Xi = new javax.swing.JTextField();
        Ea = new javax.swing.JTextField();
        Xu = new javax.swing.JTextField();
        Funcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbMetodo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();
        btnGraficarFXR = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cancelar.png"))); // NOI18N
        btncancel.setMnemonic('c');
        btncancel.setText("Cancelar");
        btncancel.setToolTipText("Cancelar / Salir");
        btncancel.setContentAreaFilled(false);
        btncancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Intervalos Cerrados");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel = PanelEffect;
        Panel.setBackground(new java.awt.Color(0, 142, 99));
        Panel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        Tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Variable");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Límite Inferior");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ea(%)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Función");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Límite Superior");

        Variable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Variable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VariableKeyTyped(evt);
            }
        });

        Xi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Xi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                XiKeyTyped(evt);
            }
        });

        Ea.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Ea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EaKeyTyped(evt);
            }
        });

        Xu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Xu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                XuKeyTyped(evt);
            }
        });

        Funcion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Funcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FuncionKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Método");

        cmbMetodo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Falsa Posición", "Bisección" }));
        cmbMetodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbMetodoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(78, 78, 78)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Variable)
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Ea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addGap(21, 21, 21)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Xi))
                            .addGap(25, 25, 25)
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25)
                            .addComponent(Xu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Xi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Xu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(30, 30, 30))
        );

        Panel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 73, 60));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Nuevo.png"))); // NOI18N
        btnNuevo.setMnemonic('n');
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Calcular los valores");
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Calculadora.png"))); // NOI18N
        btnCalcular.setMnemonic('a');
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("Calcular los valores");
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcular);

        btnGraficar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Graficar.png"))); // NOI18N
        btnGraficar.setMnemonic('g');
        btnGraficar.setText("Gráficar");
        btnGraficar.setToolTipText("Gráficar la función");
        btnGraficar.setContentAreaFilled(false);
        btnGraficar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGraficar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGraficar);

        btnGraficarFXR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGraficarFXR.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficarFXR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GraficarFXR.png"))); // NOI18N
        btnGraficarFXR.setMnemonic('g');
        btnGraficarFXR.setText("Gráficar f(xr)");
        btnGraficarFXR.setToolTipText("Gráficar la función");
        btnGraficarFXR.setContentAreaFilled(false);
        btnGraficarFXR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGraficarFXR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGraficarFXR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarFXRActionPerformed(evt);
            }
        });
        jPanel3.add(btnGraficarFXR);

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Imprimir.png"))); // NOI18N
        btnReporte.setMnemonic('r');
        btnReporte.setText("Reporte");
        btnReporte.setToolTipText("Reporte de Intervalo Abierto");
        btnReporte.setContentAreaFilled(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel3.add(btnReporte);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar / Salir");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        Panel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(882, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    KEffectPanel PanelEffect = new KEffectPanel();


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        PanelEffect.setEffect(new ZoomIn(1500));

        String[] Header = {"Iteración", "Xl", "Xu", "Xr", "f(Xr)", "f(Xl)f(Xr)", "Ea(%)"};

        Model.setColumnIdentifiers(Header);
        this.Tabla.setModel(Model);

        Funcion.requestFocus();

        PanelEffect.startEffect();

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    IntervalosCerradosDS DataSource = new IntervalosCerradosDS();

    public void Reporte(ProcesandoInfo P) throws FileNotFoundException {
        Map Parametros = new HashMap();
        Parametros.clear();
        File F = new File("");
        String RutaImagen = F.getAbsolutePath() + "/src/Grafica/GraficaCerrada.jpg";
//       System.out.println("Ruta Reporte: "+this.getClass().getResource(RutaImagen));

        InputStream Imagen = new FileInputStream(RutaImagen);
        Parametros.put("Grafica", Imagen);
        Parametros.put("Funcion", Funcion.getText().trim());
        Parametros.put("Variable", Variable.getText().trim());
        Parametros.put("EaT", Ea.getText().trim());
        Parametros.put("LimiteInferior", Xi.getText().trim());
        Parametros.put("LimiteSuperior", Xu.getText().trim());
        Parametros.put("Metodo", (String) cmbMetodo.getSelectedItem());

        for (int i = 0; i < Tabla.getRowCount(); i++) {

            String Iteracion = (String) this.Tabla.getValueAt(i, 0).toString();
            String Xl = (String) this.Tabla.getValueAt(i, 1).toString();
            String XuF = (String) this.Tabla.getValueAt(i, 2).toString();
            String Xr = (String) this.Tabla.getValueAt(i, 3).toString();
            String FXr = (String) this.Tabla.getValueAt(i, 4).toString();
            String FXlFXr = (String) this.Tabla.getValueAt(i, 5).toString();
            String EaF = (String) this.Tabla.getValueAt(i, 6).toString();

            IntervalosCerradosSetGet IC = new IntervalosCerradosSetGet(Iteracion, Xl, XuF, Xr, FXr, FXlFXr, EaF);

            DataSource.addIntervaloCerrado(IC);

        }

        String Reporte = F.getAbsolutePath() + "/src/Reporte/IntervalosCerradosReport.jasper";

        JasperPrint jp = null;

        try {
            jp = JasperFillManager.fillReport(Reporte, Parametros, DataSource);
        } catch (JRException ex) {

//                Logger.getLogger(ProveedorP.class.getName()).log(Level.SEVERE, null, ex);
        }

        JasperViewer view = new JasperViewer(jp, false);
        view.setTitle("Intervalos Cerrados");

        view.setZoomRatio((float) 0.60);
        view.setVisible(true);

        view.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        view.toFront();

        P.dispose();
    }


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void TextoDecimales(JTextField TextField, KeyEvent evt) {

        char a = evt.getKeyChar();

        if (a == '-' && TextField.getCaretPosition() != 0) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            return;
        }

        if (!Character.isDigit(a) && !Character.isISOControl(a) && a != '.' && a != '-') {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            return;
        }

        if ("0".equals(TextField.getText()) && TextField.getCaretPosition() == 1 && a != '.' && !Character.isISOControl(a)) {
            TextField.setText(TextField.getText() + ".");
//        return;
        }

        if (a == '.' && TextField.getText().contains(".")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            return;
        }

        String x1 = "";
        if (Character.isDigit(a) || (Character.isISOControl(a) && !"".equals(TextField.getText()))) {
            x1 = TextField.getText();
        }
        if (Character.isDigit(a) || (a == '.')) {
            x1 = TextField.getText().concat(String.valueOf(a));
        }

        if (!"".equals(x1)) {

            try {

                Double x = Double.parseDouble(x1);

                if (x > Double.MAX_VALUE) {
                    Toolkit.getDefaultToolkit().beep();
                    evt.consume();
                }

            } catch (NumberFormatException ex) {
                Toolkit.getDefaultToolkit().beep();
                evt.consume();
            }
        }

    }

    public void ScreenShotPanel(JPanel panel) throws IOException {

        int w = panel.getWidth();
        int h = panel.getHeight();
        BufferedImage bi = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = bi.createGraphics();
        panel.print(g);

        File F = new File("");
        String Imagen = "/src/Grafica/GraficaCerrada.jpg";
        File Carpeta = new File(F.getAbsoluteFile() + "/src/Grafica");
        Carpeta.mkdirs();
        String Ruta = F.getAbsolutePath() + Imagen;
        //   System.out.println("Ruta " + Ruta);
        File RutaF = new File(Ruta);
        ImageIO.write(bi, "JPEG", RutaF);

    }

    public void ScreenShotPanelFXR(JPanel panel) throws IOException {

        int w = panel.getWidth();
        int h = panel.getHeight();
        BufferedImage bi = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = bi.createGraphics();
        panel.print(g);

        File F = new File("");
        String Imagen = "/src/Grafica/GraficaCerradaFXR.jpg";
        File Carpeta = new File(F.getAbsoluteFile() + "/src/Grafica");
        Carpeta.mkdirs();
        String Ruta = F.getAbsolutePath() + Imagen;
        //    System.out.println("Ruta " + Ruta);
        File RutaF = new File(Ruta);
        ImageIO.write(bi, "JPEG", RutaF);

    }


    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        if (Validar()) {

            String FuncionF = Funcion.getText().trim();
            String VariableF = Variable.getText().trim();

            GraficadorClasico g = new GraficadorClasico(VariableF);
            g.setVisible(true);
            g.AgregarFuncion(FuncionF);
            try {
                ScreenShotPanel(g.PanelGrafica());
                // TODO add your handling code here:
            } catch (IOException ex) {
                // Logger.getLogger(IntervalosAbiertosP.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        if (Validar()) {
            Calcular(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void EaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EaKeyTyped
        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            Xi.requestFocus();
        }

        TextoDecimales(Ea, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_EaKeyTyped

    private void XuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_XuKeyTyped

        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            cmbMetodo.requestFocus();
        }

        TextoDecimales(Xu, evt);         // TODO add your handling code here:
    }//GEN-LAST:event_XuKeyTyped


    private void XiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_XiKeyTyped

        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            Xu.requestFocus();
        }

        TextoDecimales(Xi, evt);         // TODO add your handling code here:
    }//GEN-LAST:event_XiKeyTyped

    public void TextoVariable(JTextField TextField, KeyEvent evt) {

        char a = evt.getKeyChar();

        if (Character.isDigit(a)) {

            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }

    }


    private void VariableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VariableKeyTyped

        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            Ea.requestFocus();
        }

        TextoVariable(Variable, evt);
// TODO add your handling code here:
    }//GEN-LAST:event_VariableKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        Nuevo();
        Habilitar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    class Procesar extends Thread {

        ProcesandoInfo p;

        public Procesar(ProcesandoInfo P) {
            this.p = P;
        }

        @Override
        public void run() {

            Calcular(false);

            String FuncionF = Funcion.getText().trim();
            String VariableF = Variable.getText().trim();

            GraficadorClasico g = new GraficadorClasico(VariableF);
            g.setVisible(true);
            g.toBack();
            g.AgregarFuncion(FuncionF);
            try {
                ScreenShotPanel(g.PanelGrafica());
                // TODO add your handling code here:
            } catch (IOException ex) {
                // Logger.getLogger(IntervalosAbiertosP.class.getName()).log(Level.SEVERE, null, ex);
            }

            g.dispose();

            try {
                Reporte(this.p);        // TODO add your handling code here:
            } catch (FileNotFoundException ex) {
                //  Logger.getLogger(IntervalosAbiertosP.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        if (Validar()) {

            ProcesandoInfo p = new ProcesandoInfo();
            p.setVisible(true);

            p.toFront();
            new Procesar(p).start();

//            try {
//                GraficarFXR();
//            } catch (IOException ex) {
//             //   Logger.getLogger(IntervalosCerradosP.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    public void Habilitar() {
        Funcion.setEnabled(true);
        Variable.setEnabled(true);
        Xi.setEnabled(true);
        Xu.setEnabled(true);
        Ea.setEnabled(true);
        cmbMetodo.setEnabled(true);
    }

    public void Deshabilitar() {
        Funcion.setEnabled(false);
        Variable.setEnabled(false);
        Xi.setEnabled(false);
        Xu.setEnabled(false);
        Ea.setEnabled(false);
        cmbMetodo.setEnabled(false);
    }

    public boolean Validar() {
        String Fun, Var, XiF, XuF, EaF, Metodo;

        Fun = Funcion.getText().trim();
        Var = Variable.getText().trim();
        XiF = Xi.getText().trim();
        XuF = Xu.getText().trim();
        EaF = Ea.getText().trim();
        Metodo = (String) cmbMetodo.getSelectedItem();

        if ("".equals(Fun) || "".equals(Var) || "".equals(XiF) || "".equals(XuF) || "".equals(EaF) || "<Seleccione>".equals(Metodo)) {

            JOptionPane.showMessageDialog(this, "Complete todos los datos", "Complete", JOptionPane.ERROR_MESSAGE);
            return false;

        }

        return true;
    }

    public void GraficarFXR() throws IOException {

        if (Validar()) {
            Calcular(false);
            Graficador2D GF2 = new Graficador2D();
            GF2.Graficador2D("Grafica de f(Xr)", "", X1, Y1);
            ScreenShotPanelFXR(GF2.getPanelGrafica());

        }
    }

    double[] X1, Y1;


    private void btnGraficarFXRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarFXRActionPerformed
        try {
            GraficarFXR(); // TODO add your handling code here:
        } catch (IOException ex) {
            //    Logger.getLogger(IntervalosCerradosP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGraficarFXRActionPerformed

    private void cmbMetodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMetodoKeyTyped
        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            if (Validar()) {
                Calcular(true);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoKeyTyped

    private void FuncionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FuncionKeyTyped
        char a = evt.getKeyChar();

        if (a == KeyEvent.VK_ENTER) {

            Variable.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionKeyTyped

    public void Calcular(boolean flag) {
        String funcion = Funcion.getText();
        String val = Variable.getText();
        double xl, xu, xr, xrAnt, FxlFxr, ea;
        try {
            xl = Double.parseDouble(Xi.getText());
            xu = Double.parseDouble(Xu.getText());
            ea = Double.parseDouble(Ea.getText());
        } catch (NumberFormatException nf) {
            // JOptionPane.showMessageDialog(null, "Error de caracteres en los limites o en el valor Ea de referencia", "Error", JOptionPane.ERROR_MESSAGE);
            String Msj = "Error de caracteres en los límites o en el valor Ea de referencia";
            Error Er = new Error(this, true, Msj);
            Er.setVisible(true);
            Er.toFront();
            return;
        }

        if (isParser(funcion, val, xl)) {
            //  JOptionPane.showMessageDialog(null, "Error no se puede evaluar la funcion", "Error", JOptionPane.ERROR_MESSAGE);
            String Msj = "Error, no se puede evaluar la función";
            Error Er = new Error(this, true, Msj);
            Er.setVisible(true);
            Er.toFront();
            return;
        }

        double[] x, y;
       xr =0;
        switch (this.cmbMetodo.getSelectedIndex()) {

            case 1:
                xr = CalculoFalsaPosicion(funcion, xl, xu, val);
                
                break;

            case 2:
                xr = CalculoBiseccion(xl, xu);
                break;

            default:
                break;
        }
        FxlFxr = Eval(funcion, val, xl) * Eval(funcion, val, xr);
        Limpiar();
        Model.addRow(new Object[]{1, xl, xu, xr, Eval(funcion, val, xr), FxlFxr, "-"});
        int i = 1;
        do {
            i++;
            if (FxlFxr < 0) {
                xu = xr;
            } else if (FxlFxr == 0) {
                return;
            } else if (FxlFxr > 0) {
                xl = xr;
            }

            xrAnt = xr;
            switch (this.cmbMetodo.getSelectedIndex()) {

                case 1:
                    xr = CalculoFalsaPosicion(funcion, xl, xu, val);
                    break;

                case 2:
                    xr = CalculoBiseccion(xl, xu);
                    break;

                default:
                    break;
            }

            FxlFxr = Eval(funcion, val, xl) * Eval(funcion, val, xr);

            Model.addRow(new Object[]{i, xl, xu, xr, Eval(funcion, val, xr), FxlFxr, Math.abs(CalculoDiferencia(xr, xrAnt))});

        } while (Math.abs(CalculoDiferencia(xr, xrAnt)) >= ea);

        x = new double[i];
        y = new double[i];

        for (int j = Model.getRowCount() - 1; j >= 0; j--) {
            x[j] = Double.parseDouble(Model.getValueAt(j, 3).toString());
            y[j] = Double.parseDouble(Model.getValueAt(j, 4).toString());
        }

        this.X1 = x;
        this.Y1 = y;
        this.Tabla.setModel(Model);

        if (flag) {
            JOptionPane.showMessageDialog(this, Conclu(xr, CalculoDiferencia(xr, xrAnt),
                    Model.getRowCount()), "Conclusión", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    public void Nuevo() {
        Model.setRowCount(0);
        Tabla.setModel(Model);

        Funcion.setText("");
        Variable.setText("");
        Ea.setText("");
        Xi.setText("");
        Xu.setText("");
        cmbMetodo.setSelectedIndex(0);

        Funcion.requestFocus();
    }

    public String Conclu(double xr, double Ea, int it) {

        return "Se encontro el valor buscado " + xr + " a la " + it + " iteracion con un error relativo de " + Ea + " %";
    }

    public void Limpiar() {
        for (int i = Model.getRowCount() - 1; i >= 0; i--) {
            Model.removeRow(i);
        }
        Tabla.setModel(Model);
    }

    public double CalculoDiferencia(double va, double vant) {
        return ((va - vant)) / va * 100;
    }

    public double CalculoFalsaPosicion(String Funcion, double Xl, double Xu, String Val) {
        double Xr;

        Xr = Xu - (Eval(Funcion, Val, Xu) * (Xl - Xu) / (Eval(Funcion, Val, Xl) - Eval(Funcion, Val, Xu)));

        return Xr;
    }

    public double CalculoBiseccion(double Xl, double Xu) {
        return (Xl + Xu) / 2;
    }

    DefaultTableModel Model = new DefaultTableModel() {

//        
//    Class[] types = new Class [] {
//  
//        java.lang.Boolean.class,java.lang.String.class, java.lang.String.class, 
//        java.lang.String.class, java.lang.String.class, java.lang.String.class, 
//        java.lang.String.class
//    };
// 
//
//    @Override
//    public Class getColumnClass(int columnIndex) {
//        return types [columnIndex];
//    }
        @Override
        public boolean isCellEditable(int row, int column) {

//     if(column == 0){
//            return true;
//        }else{
//            return false;
//    }
//all cells false
            return false;

        }
    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IntervalosAbiertosP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        
        try {

            UIManager.setLookAndFeel(new com.nilo.plaf.nimrod.NimRODLookAndFeel());

        } catch (UnsupportedLookAndFeelException e) {
            //System.out.println("NO SE PUEDE CARGAR");      
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntervalosCerradosP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ea;
    private javax.swing.JTextField Funcion;
    private javax.swing.JPanel Panel;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Variable;
    private javax.swing.JTextField Xi;
    private javax.swing.JTextField Xu;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnGraficarFXR;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btncancel;
    private javax.swing.JComboBox cmbMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
