/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import JLayer.WaitLayerUI;
import com.keffect.effects.animatedEffects.Shape;
import com.keffectpanel.KEffectPanel;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLayer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.edisoncor.gui.util.Avatar;

/**
 *
 * @author Reymundo Tenorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         
        initComponents();
        
        
        jlayer = new JLayer<>(this.jPanel1, wui);
        stopper = new Timer(800, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                wui.stop();
            }
        });
        
        MenuPrincipal.jlayer.setSize(this.jPanel1.getX(), this.jPanel1.getY());
        this.add(jlayer);
        
        reloj(); 
       
    }
    
     public static void setWaitProcess() {
        wui.start();
        if (!stopper.isRunning()) {
            stopper.start();
        }
    }
     
      public static void setProcess() {
        setWaitProcess();
    }
      
    static WaitLayerUI wui = new WaitLayerUI();
    static Timer stopper ;
    static JLayer<JPanel> jlayer;
    
    
   
 
      public void Iniciar(){
        
         
      MyAvatar.setAmount(0);
      //MyAvatar.setOpaque(true);
        
      
      List Avatares = new ArrayList();

     
        Avatares.add(new Avatar("Intervalos Abiertos", LoadImage("/Iconos/Abierto.png")));
        Avatares.add(new Avatar("Intervalos Cerrados", LoadImage("/Iconos/Cerrado.png")));
  
  
      MyAvatar.setAvatars(Avatares);
     
       
      
        
    }
      
      private static Image LoadImage(String Filename){
        try{ 
            
            return ImageIO.read(JFrame.class.getResource(Filename));
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MyAvatar = new org.edisoncor.gui.panel.PanelAvatarChooser();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú Principal");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1 = PanelEffect;
        jPanel1.setLayout(new java.awt.BorderLayout());

        MyAvatar.setColorPrimario(new java.awt.Color(102, 102, 255));
        MyAvatar.setColorSecundario(new java.awt.Color(0, 0, 153));
        MyAvatar.setGradiente(org.edisoncor.gui.panel.Panel.Gradiente.CIRCULAR);
        MyAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo.JPG"))); // NOI18N
        MyAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAvatarMouseClicked(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MyAvatarLayout = new javax.swing.GroupLayout(MyAvatar);
        MyAvatar.setLayout(MyAvatarLayout);
        MyAvatarLayout.setHorizontalGroup(
            MyAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAvatarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        MyAvatarLayout.setVerticalGroup(
            MyAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAvatarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jPanel1.add(MyAvatar, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(802, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MyAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAvatarMouseClicked

    
        
        if(evt.getClickCount()==2 && evt.getButton()==MouseEvent.BUTTON1){
            switch(MyAvatar.getAvatarIndex()+1){
            
             case 1 : 
                 IntervalosAbiertosP Pr = new IntervalosAbiertosP();
                
                 Pr.setVisible(true);
            
                 break;
                 
             case 2 : 
                 IntervalosCerradosP Ej = new IntervalosCerradosP();
               
                 Ej.setVisible(true);
                 
                 break;
                 
          
                 
             default:  break;
            
                
            }
       
           
             }
            
    }//GEN-LAST:event_MyAvatarMouseClicked

    
java.util.Calendar calendario; 
int dia, mes, año, hora, minutos, segundos; 

    public void reloj() { 
calendario = new java.util.GregorianCalendar(); 
segundos = calendario.get(Calendar.SECOND); 
javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() { 
        
        
@ Override 
public void actionPerformed(java.awt.event.ActionEvent ae) { 
java.util.Date actual = new java.util.Date(); 
calendario.setTime(actual); 
dia = calendario.get(Calendar.DAY_OF_MONTH); 
mes = (calendario.get(Calendar.MONTH) + 1); 
año = calendario.get(Calendar.YEAR); 
hora = calendario.get(Calendar.HOUR_OF_DAY); 
minutos = calendario.get(Calendar.MINUTE); 
segundos = calendario.get(Calendar.SECOND); 
//String hour = String.format("%02d : %02d : %02d", hora, minutos, segundos); 
SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a  EEEEEEEEE, dd 'de' MMMMM 'de' yyyy");

String fecha = format.format(actual);

lblFecha.setText(fecha);

//String hour = String.format("%tI : %tM : %tS %Tp", calendario); 
//String date = String.format("%02d / %02d / %02d", dia, mes, año); 
//label.setText("<html><center>" + hour + "<br>" + date); 
 
} 
}); 

timer.start(); 
} 

    
    KEffectPanel PanelEffect = new KEffectPanel();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
     
        
      this.setResizable(false);
     
       Iniciar();
       
      PanelEffect.setEffect(new Shape(1500));
      PanelEffect.startEffect();
      

      setProcess();
      
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
Salir();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void Salir(){
        
 int f = JOptionPane.showConfirmDialog(this,"Está Seguro Que Desea Salir?","Salir",JOptionPane.YES_NO_OPTION);
        
               
        if(f==JOptionPane.YES_OPTION){
     
            
                
            System.exit(0);
                }
               
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {

            UIManager.setLookAndFeel(new com.nilo.plaf.nimrod.NimRODLookAndFeel());

        } catch (UnsupportedLookAndFeelException e) {
            //System.out.println("NO SE PUEDE CARGAR");      
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelAvatarChooser MyAvatar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    // End of variables declaration//GEN-END:variables
}
